include: package:very_good_analysis/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    avoid_bool_literals_in_conditional_expressions: false